### ISSUE TITLE
-

### ISSUE THREAD

**Issue by Tanishq-JM** [MD14pro/Jarvis.py#8]

**Comment by MD14pro** [comment]
Is your image stored in the same directory as the python file?

**Comment by Tanishq-JM** [comment]
yes

**Comment by Tanishq-JM** [comment]
faces/img

**Comment by MD14pro** [comment]
Are all modules downloaded and pip latest version?
Are the app permissions granted?

**Comment by Tanishq-JM** [comment]
yes
i am still facing the same problem i have reinstalled python 5-6 times

**Comment by Tanishq-JM** [comment]
replace the code line,
rgb_small_frame = small_frame[:, :, ::-1] 
with below code line,
rgb_small_frame = cv2.cvtColor(small_frame, cv2.COLOR_BGR2RGB) issue resolved THanks for your time brother

**Comment by Tanishq-JM** [comment]
replace the code line,
rgb_small_frame = small_frame[:, :, ::-1]
with below code line,
rgb_small_frame = cv2.cvtColor(small_frame, cv2.COLOR_BGR2RGB) issue resolved THanks for your time brother
